### ISSUE TITLE
See StackTrace

### ISSUE THREAD

**Issue by DTS-MC** [Nathat23/StackMob-2#1]
[22:39:48] [Server thread/ERROR]: Could not pass event ItemSpawnEvent to StackMob v2.0.10
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-7754231-362ed32]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-7754231-362ed32]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [minecraft_server.jar:git-Spigot-7754231-362ed32]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [minecraft_server.jar:git-Spigot-7754231-362ed32]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callItemSpawnEvent(CraftEventFactory.java:311) [minecraft_server.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.World.addEntity(World.java:1044) [minecraft_server.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.WorldServer.addEntity(WorldServer.java:1112) [minecraft_server.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.World.addEntity(World.java:1013) [minecraft_server.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.Entity.a(Entity.java:1763) [minecraft_server.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.Entity.a(Entity.java:1746) [minecraft_server.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.Entity.a(Entity.java:1741) [minecraft_server.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.EntityChicken.n(EntityChicken.java:70) [minecraft_server.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1939) [minecraft_server.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:246) [minecraft_server.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1633) [minecraft_server.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.World.h(World.java:1603) [minecraft_server.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1437) [minecraft_server.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665) [minecraft_server.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [minecraft_server.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [minecraft_server.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [minecraft_server.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [minecraft_server.jar:git-Spigot-7754231-362ed32]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.IllegalArgumentException: Cannot spawn an entity for org.bukkit.entity.Item
        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.createEntity(CraftWorld.java:1194) ~[minecraft_server.jar:git-Spigot-7754231-362ed32]
        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.spawn(CraftWorld.java:1219) ~[minecraft_server.jar:git-Spigot-7754231-362ed32]
        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.spawn(CraftWorld.java:856) ~[minecraft_server.jar:git-Spigot-7754231-362ed32]
        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.spawnEntity(CraftWorld.java:356) ~[minecraft_server.jar:git-Spigot-7754231-362ed32]
        at uk.antiperson.stackmob.tools.DropTools.dropEggs(DropTools.java:67) ~[?:?]
        at uk.antiperson.stackmob.events.entity.ItemDrop.onEggDrop(ItemDrop.java:29) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor376.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[minecraft_server.jar:git-Spigot-7754231-362ed32]
        ... 22 more

**Comment by Nathat23** [comment]
This should be fixed in the latest release.
