### ISSUE TITLE
Could not load 'plugins\StackMob-2.4.2-SNAPSHOT.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by xTunio** [Nathat23/StackMob-2#119]
**Describe the bug**
Server couldn't load plugin

Output from console log
```
[23:09:46] [Server thread/ERROR]: Could not load 'plugins\StackMob-2.4.2-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NullPointerException
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[PaperSpigot-latest.jar:git-Paper-335]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[PaperSpigot-latest.jar:git-Paper-335]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) ~[PaperSpigot-latest.jar:git-Paper-335]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:326) ~[PaperSpigot-latest.jar:git-Paper-335]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:230) ~[PaperSpigot-latest.jar:git-Paper-335]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[PaperSpigot-latest.jar:git-Paper-335]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:324) ~[PaperSpigot-latest.jar:git-Paper-335]
	at uk.antiperson.stackmob.tools.StickTools.<init>(StickTools.java:22) ~[?:?]
	at uk.antiperson.stackmob.StackMob.<init>(StackMob.java:36) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_181]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:94) ~[PaperSpigot-latest.jar:git-Paper-335]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[PaperSpigot-latest.jar:git-Paper-335]
	... 6 more
```

**Bukkit/Spigot AND StackMob version:**

/version:
```
[16:44:52] [Server thread/INFO]: This server is running Paper version git-Paper-335 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
[16:44:52] [Server thread/INFO]: Previous version: git-Paper-316 (MC: 1.13.1)
[16:44:52] [Server thread/INFO]: You are 11 version(s) behind
```
SM Version: StackMob-2.4.2-SNAPSHOT

**Comment by Nathat23** [comment]
Delete your config.yml and lang.yml files, then restart.
