### ISSUE TITLE
java.util.ConcurrentModificationException: null

### ISSUE THREAD

**Issue by Ghost-chu** [Nathat23/StackMob-2#130]
[08:38:07 WARN]: [StackMob] Plugin StackMob v2.4.7 generated an exception while executing task 21
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_192]
at java.util.HashMap$EntryIterator.next(HashMap.java:1479) ~[?:1.8.0_192]
at java.util.HashMap$EntryIterator.next(HashMap.java:1477) ~[?:1.8.0_192]
at uk.antiperson.stackmob.tools.config.CacheFile.saveCache(CacheFile.java:39) ~[?:?]
at uk.antiperson.stackmob.tasks.CacheSave.run(CacheSave.java:15) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[PaperSpigot-1.13.2-R0.1.jar:git-Paper-405]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[PaperSpigot-1.13.2-R0.1.jar:git-Paper-405]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[PaperSpigot-1.13.2-R0.1.jar:git-Paper-405]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192

**Comment by Nathat23** [comment]
This will be fixed in next release.
