### ISSUE TITLE
/sm update error

### ISSUE THREAD

**Issue by LogGits** [Nathat23/StackMob-2#139]
**Describe the bug**
Error while using /sm update:
```
WARN 21/11/2018 08:10:22
08:10:22java.io.FileNotFoundException: https://api.spiget.org/v2/resources/29999/download
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
at java.net.URL.openStream(URL.java:1045)
at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1478)
at uk.antiperson.stackmob.tools.UpdateChecker.update(UpdateChecker.java:45)
at uk.antiperson.stackmob.Commands.onCommand(Commands.java:74)
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732)
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:694)
at net.minecraft.server.v1_13_R2.DedicatedServer.aU(DedicatedServer.java:483)
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:440)
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)
at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**
/sm update

**Expected behavior**
update the plugin

**Bukkit/Spigot AND StackMob version:**
paper 1.13.2 build 456
stackmob 3.1.0

**Comment by Nathat23** [comment]
Not much that I can do about this since the update server is out of my control and the owner appears to be ignoring messages.

**Comment by Nathat23** [comment]
Should be fixed according to https://github.com/SpiGetOrg/Spiget/issues/17 when the next update is released.
