### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LogGits** [Nathat23/StackMob-2#164]
Getting an error when a player dies.
```
ERROR 18/12/2018 22:17:17
22:17:17Could not pass event PlayerDeathEvent to StackMob v3.2.0
Console 18/12/2018 22:17:17
22:17:17org.bukkit.event.EventException: null
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-486]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-486]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-486]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-486]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:614) ~[patched_1.13.2.jar:git-Paper-486]
at net.minecraft.server.v1_13_R2.EntityPlayer.die(EntityPlayer.java:515) ~[patched_1.13.2.jar:git-Paper-486]
at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:1088) ~[patched_1.13.2.jar:git-Paper-486]
at net.minecraft.server.v1_13_R2.EntityHuman.damageEntity(EntityHuman.java:820) ~[patched_1.13.2.jar:git-Paper-486]
at net.minecraft.server.v1_13_R2.EntityPlayer.damageEntity(EntityPlayer.java:655) ~[patched_1.13.2.jar:git-Paper-486]
at net.minecraft.server.v1_13_R2.EntityLiving.c(EntityLiving.java:1375) ~[patched_1.13.2.jar:git-Paper-486]
at net.minecraft.server.v1_13_R2.EntityHuman.c(EntityHuman.java:1644) ~[patched_1.13.2.jar:git-Paper-486]
at net.minecraft.server.v1_13_R2.Block.fallOn(Block.java:582) ~[patched_1.13.2.jar:git-Paper-486]
at net.minecraft.server.v1_13_R2.Entity.a(Entity.java:1097) ~[patched_1.13.2.jar:git-Paper-486]
at net.minecraft.server.v1_13_R2.EntityLiving.a(EntityLiving.java:208) ~[patched_1.13.2.jar:git-Paper-486]
at net.minecraft.server.v1_13_R2.EntityPlayer.a(EntityPlayer.java:832) ~[patched_1.13.2.jar:git-Paper-486]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1085) ~[patched_1.13.2.jar:git-Paper-486]
at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.13.2.jar:git-Paper-486]
at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[patched_1.13.2.jar:git-Paper-486]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-486]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-486]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-486]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-486]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-486]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-486]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer cannot be cast to org.bukkit.entity.Mob
at uk.antiperson.stackmob.entity.multiplication.DropTools.calculateDrops(DropTools.java:51) ~[?:?]
at uk.antiperson.stackmob.listeners.entity.DeathEvent.multiplication(DeathEvent.java:51) ~[?:?]
at uk.antiperson.stackmob.listeners.entity.DeathEvent.onDeath(DeathEvent.java:38) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor153.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-486]
... 26 more
```

**Comment by Nathat23** [comment]
Did this happen after the stack tool was used on the player in #163 ?

**Comment by LogGits** [comment]
Yes, when that player died, this error was in console

**Comment by Nathat23** [comment]
Fixed.

**Comment by LogGits** [comment]
@Nathat23 how i remove the attribute that it set on the player. Where is it stored?

**Comment by Nathat23** [comment]
1. Find the UUID of the player. (this is given when they log in)
2. Stop the server
3. Go to the cache.yml file in the StackMob plugin folder.
4. Ctrl+F the UUID, and remove the entire line.
5. Start the server again.
