### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by unsivilaudio** [Nathat23/StackMob-2#4]
Spigot 1.12.2 latest build

`[11:26:23 WARN]: [StackMob] Task #2 for StackMob v2.1.1 generated an exception
java.lang.NullPointerException: null
        at uk.antiperson.stackmob.tasks.TagUpdater.run(TagUpdater.java:58) ~[?:?]`

Stackmob v2.1.1

**Comment by Nathat23** [comment]
Could you provide a full stack trace?

**Comment by unsivilaudio** [comment]
Not much more to it than that.  About 50 of these in a matter of seconds...

`[11:26:41 WARN]: [StackMob] Task #2 for StackMob v2.1.1 generated an exception
java.lang.NullPointerException: null
        at uk.antiperson.stackmob.tasks.TagUpdater.run(TagUpdater.java:58) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-93e20b3-31d3159]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]`

**Comment by Nathat23** [comment]
Is lang.yml enabled?

**Comment by unsivilaudio** [comment]
Just for anyone experiencing the issue, delete your configuration file and let it rebuild.  It appears to have been modified significantly since SM 1.8 versions and something is incompatible.
