### ISSUE TITLE
mcMMO error

### ISSUE THREAD

**Issue by andris155** [Nathat23/StackMob-2#48]
```
[20:36:39] [Server thread/WARN]: [mcMMO] Task #23 for mcMMO v1.5.09-SNAPSHOT generated an exception
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_161]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1476) ~[?:1.8.0_161]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1474) ~[?:1.8.0_161]
	at com.gmail.nossr50.runnables.skills.BleedTimerTask.run(BleedTimerTask.java:24) ~[mcMMO.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1414]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) [patched_1.12.2.jar:git-Paper-1414]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1414]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1414]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1414]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1414]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

**Comment by Nathat23** [comment]
I don't see StackMob anywhere in that log?

**Comment by andris155** [comment]
I use StackMob -  mcMMO Write this error.
I remove StackMob -  mcMMO no write this error.
