### ISSUE TITLE
StackMob Task #25 Bug 

### ISSUE THREAD

**Issue by TheRealPixoid** [Nathat23/StackMob-2#71]
24.06 14:47:23 [Server] WARN [StackMob] Task #25 for StackMob v2.2.11 generated an exception
24.06 14:47:23 [Server] INFO java.lang.IndexOutOfBoundsException: Index: 0
24.06 14:47:23 [Server] INFO at java.util.Collections$EmptyList.get(Collections.java:4454) ~[?:1.8.0_171]
24.06 14:47:23 [Server] INFO at uk.antiperson.stackmob.tasks.StackTask.run(StackTask.java:57) ~[?:?]
24.06 14:47:23 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot_1.12.jar:git-Spigot-596221b-9a1fc1e]
24.06 14:47:23 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot_1.12.jar:git-Spigot-596221b-9a1fc1e]
24.06 14:47:23 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot_1.12.jar:git-Spigot-596221b-9a1fc1e]
24.06 14:47:23 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot_1.12.jar:git-Spigot-596221b-9a1fc1e]
24.06 14:47:23 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot_1.12.jar:git-Spigot-596221b-9a1fc1e]
24.06 14:47:23 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot_1.12.jar:git-Spigot-596221b-9a1fc1e]
24.06 14:47:23 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

I haven't noticed anything wrong with the plugin or something not working but my console gets flooded with this every 5 seconds.

**Comment by Nathat23** [comment]
Does this occur with the latest version? (2.2.12)

**Comment by TheRealPixoid** [comment]
No it started occurring with the version you released yesterday titled "Plenty of bug fixes."

**Comment by Nathat23** [comment]
I released a new version a few hours ago.

**Comment by LogGits** [comment]
Also getting this issue on the latest build:
```
WARN 25/06/2018 17:12:16
17:12:16[StackMob] Task #2756 for StackMob v2.2.12 generated an exception
Console 25/06/2018 17:12:16
17:12:16java.lang.IllegalArgumentException: Career id must be greater than 0
at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.12.2.jar:git-Paper-1468]
at org.bukkit.craftbukkit.v1_12_R1.entity.CraftVillager.getCareer(CraftVillager.java:133) ~[patched_1.12.2.jar:git-Paper-1468]
at org.bukkit.craftbukkit.v1_12_R1.entity.CraftVillager.getCareer(CraftVillager.java:54) ~[patched_1.12.2.jar:git-Paper-1468]
at uk.antiperson.stackmob.tools.EntityTools.notMatching(EntityTools.java:72) ~[StackMob-2.2.12-SNAPSHOT.jar:?]
at uk.antiperson.stackmob.tools.EntityTools.notEnoughNearby(EntityTools.java:336) ~[StackMob-2.2.12-SNAPSHOT.jar:?]
at uk.antiperson.stackmob.listeners.entity.SpawnEvent$1.run(SpawnEvent.java:92) ~[StackMob-2.2.12-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1468]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) [patched_1.12.2.jar:git-Paper-1468]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1468]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1468]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1468]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1468]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

**Comment by Nathat23** [comment]
Has this been fixed? @TheRealPixoid

**Comment by TheRealPixoid** [comment]
No, still occurring.
