### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LogGits** [Nathat23/StackMob-2#73]
**Describe the bug**
Error that spams console:
```
WARN 25/06/2018 17:12:16
17:12:16[StackMob] Task #2756 for StackMob v2.2.12 generated an exception
Console 25/06/2018 17:12:16
17:12:16java.lang.IllegalArgumentException: Career id must be greater than 0
at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.12.2.jar:git-Paper-1468]
at org.bukkit.craftbukkit.v1_12_R1.entity.CraftVillager.getCareer(CraftVillager.java:133) ~[patched_1.12.2.jar:git-Paper-1468]
at org.bukkit.craftbukkit.v1_12_R1.entity.CraftVillager.getCareer(CraftVillager.java:54) ~[patched_1.12.2.jar:git-Paper-1468]
at uk.antiperson.stackmob.tools.EntityTools.notMatching(EntityTools.java:72) ~[StackMob-2.2.12-SNAPSHOT.jar:?]
at uk.antiperson.stackmob.tools.EntityTools.notEnoughNearby(EntityTools.java:336) ~[StackMob-2.2.12-SNAPSHOT.jar:?]
at uk.antiperson.stackmob.listeners.entity.SpawnEvent$1.run(SpawnEvent.java:92) ~[StackMob-2.2.12-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1468]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) [patched_1.12.2.jar:git-Paper-1468]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1468]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1468]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1468]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1468]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

**Bukkit/Spigot version:**
1.12.2

**Comment by Nathat23** [comment]
Do you have any NPC plugins? This isn't a problem directly related with StackMob.

**Comment by LogGits** [comment]
Yes i am using Citizens2 and ShopKeepers. The error only started happening when i updated stackmob.

**Comment by Nathat23** [comment]
You are using the absolute latest server build, right?

**Comment by LogGits** [comment]
Yes, one of the latest paperspigot builds, specifically build 1468 on version 1.12.2.

**Comment by Nathat23** [comment]
I have made an issue on the Spigot issue tracker, as this is out of my control.
https://hub.spigotmc.org/jira/browse/SPIGOT-3991

**Comment by LogGits** [comment]
I cannot find this issue in the jira, link doesn't open.

**Comment by Nathat23** [comment]
Could you recreate the error while using spigot, since that is what that issue tracker is for?

**Comment by Nathat23** [comment]
Please respond @LogGits

**Comment by LogGits** [comment]
Hey @Nathat23, my server is running on paperspigot 1.12.2 build 1468. I dont use regular spigot. This error only started happenong after updating to the latest StackMob build. Would you like me to make a report to the paperspigot devs?

**Comment by Nathat23** [comment]
Please do make a paperspigot report. Although it would be better to test with regular spigot so the issue can be fixed upstream and benefits more users.

This is nothing to do this plugins, this is an issue with spigot itself.

**Comment by Nathat23** [comment]
@LogGits Can you update?

**Comment by Nathat23** [comment]
I will close this since there isn't anything I can do unfortunately. Another plugin is overriding/changing it.
