### ISSUE TITLE
Task #245 for StackMob v2.2.12 generated an exception

### ISSUE THREAD

**Issue by serposter** [Nathat23/StackMob-2#81]
[StackMob] Task #245 for StackMob v2.2.12 generated an exception
java.lang.NoSuchMethodError: org.bukkit.entity.Villager.getCareer()Lorg/bukkit/entity/Villager$Career;
        at uk.antiperson.stackmob.tools.EntityTools.notMatching(EntityTools.java:72) ~[?:?]
        at uk.antiperson.stackmob.tools.EntityTools.notEnoughNearby(EntityTools.java:336) ~[?:?]
        at uk.antiperson.stackmob.listeners.entity.SpawnEvent$1.run(SpawnEvent.java:92) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-3d850ec-809c399]

**Comment by Nathat23** [comment]
Sorry, it is not.

You need to upgrade your server version.

**Comment by serposter** [comment]
Server version 1.12.2

**Comment by Nathat23** [comment]
I mean the build
