### ISSUE TITLE
Just a nullpointer

### ISSUE THREAD

**Issue by sandor111** [Nathat23/StackMob-2#90]
**Describe the bug**
My console is getting spammed with this nullpointer:
`Could not pass event EntityDeathEvent to StackMob v2.2.14
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[paper.jar:git-PaperSpigot-"4c7641d"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[paper.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paper.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [paper.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [paper.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:378) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityLiving.die(EntityLiving.java:884) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:822) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityLiving.K(EntityLiving.java:180) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityInsentient.K(EntityInsentient.java:150) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.Entity.t_(Entity.java:263) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1457) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityInsentient.t_(EntityInsentient.java:194) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1650) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.World.g(World.java:1617) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1450) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:600) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:846) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [paper.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at uk.antiperson.stackmob.tools.DropTools.calculateDrops(DropTools.java:24) ~[StackMob-2.2.14-SNAPSHOT.jar:?]
	at uk.antiperson.stackmob.listeners.entity.DeathEvent.multiplication(DeathEvent.java:80) ~[StackMob-2.2.14-SNAPSHOT.jar:?]
	at uk.antiperson.stackmob.listeners.entity.DeathEvent.onDeath(DeathEvent.java:50) ~[StackMob-2.2.14-SNAPSHOT.jar:?]
	at sun.reflect.GeneratedMethodAccessor339.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[paper.jar:git-PaperSpigot-"4c7641d"]
	... 21 more`

**Bukkit/Spigot AND StackMob version:**
Stackmob V2.2.14 and paper 1.8.8

My minecraft faction servers:
https://factionservers.net

**Comment by Nathat23** [comment]
Do you have a plugin that modifies entity drops?

**Comment by sandor111** [comment]
Yes Editdrops https://www.spigotmc.org/resources/edit-drops-1-0-6-gui-edit-all-mob-drops-easily.34561/

**Comment by Nathat23** [comment]
I'm guessing you have made one entity not have any drops?

**Comment by sandor111** [comment]
Thanks that's probably the issue, if not I'll let you know by tomorrow :).

**Comment by Nathat23** [comment]
Closed because of resolution.
